DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS book;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE book (
    ISBN CHAR(13) PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT,
    publisher TEXT,
    stock INTEGER DEFAULT 1
);
